#!/bin/bash

# #############################################################################
# init var and env
# #############################################################################

source backend/venv/bin/activate

if ! geonature db status 1> /dev/null 2>&1; then
    echo >&2 -e "// /////////////////////////////////////////"
    echo >&2 -e "//"
    echo >&2 -e "// Alembic is dirty"
    echo >&2 -e "// Maybe you forgot to downgrade alembic ?"
    echo >&2 -e "//"
    echo >&2 -e "// /////////////////////////////////////////"
    git checkout -
    exit 1
else
    exit 0
fi

